[workspace]
resolver = "2"
members = ["crates/vaultzip-core", "crates/vaultzip-cli", "crates/vaultzip-gui"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/blackantrax/vaultzip"
rust-version = "1.85"

[profile.release]
lto = true
codegen-units = 1
strip = true
panic = "abort"
