[package]
name = "vaultzip-gui"
description = "VaultZip desktop application"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
build = "build.rs"

[[bin]]
name = "vaultzip-gui"
path = "src/main.rs"

[dependencies]
vaultzip-core = { path = "../vaultzip-core" }
eframe = { version = "0.36", default-features = false, features = ["glow", "default_fonts", "x11"] }
rfd = { version = "0.17", default-features = false, features = ["gtk3"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.56"

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"

[dev-dependencies]
tempfile = "3"
